### PR TITLE
chore: add testrun for symfony 7

### PR DESCRIPTION
**Pull request by Chris53897**
Please see https://github.com/php-http/client-common/pull/232#issuecomment-1833494282

Support for Symfony 7 is added in "phpspec/phpspec" 7.5.0
https://github.com/phpspec/phpspec/releases/tag/7.5.0

### CODE REVIEW

**Comment by dbu** [comment]
something is not working with those "LTS" builds - https://github.com/php-http/client-common/actions/runs/7600541313/job/20722422472?pr=237 is the one that says symfony 7, but it installs symfony 3 things :scream: 

we should probably set up flex with shivammatur like they do here https://github.com/doctrine/DoctrineBundle/commit/42f5834825eaa967af833722c336d5dd05cbd4f3 and make sure the major version is enforced.

**Comment by dbu** [comment]
the problem with the current setup: we install flex at the same time as updating the dependencies, so flex is not yet present and does not enforce versions.

**Comment by Chris53897** [comment]
@dbu
I think `composer global` was the missing part. But maybe you are right too.
Because i did remove more parts, because i think they are obsolete.
Please have a look if i did it correct.

I changed Symfony LTS according to the real LTS.
https://symfony.com/releases

**Review by dbu — APPROVED** [review]
ah, `global` is a solution as well.

and we missed to set the `SYMFONY_REQUIRE` variable? thanks for cleaning this up!

**Pull request merged**
