### PR TITLE
Replacement upgrade phpspec-code-coverage

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #188
| License         | MIT

Co-Authored-By: Dan Michael O. Heggø <d.m.heggo@ub.uio.no>

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Travis didn't run?

**Comment by dbu** [comment]
weird. maybe its still in the queue? it did run on the other MR that you marked as draft, right? or maybe it is running but not updating github?

**Comment by GrahamCampbell** [comment]
Travis does seem to have triggered, but not pushed the build status to GitHub: https://travis-ci.org/github/php-http/client-common/builds/703951705.

**Comment by GrahamCampbell** [comment]
Build passed:

image

**Comment by dbu** [comment]
great, thanks!

**Pull request merged**
