### PR TITLE
Allow using Symfony 7 dependencies

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| Documentation   | -
| License         | MIT

Similar to https://github.com/php-http/curl-client/pull/82. This is needed to use this package in Symfony 7 applications.

### CODE REVIEW

**Comment by Chris53897** [comment]
Could you please add a testrun for symfony 7?

**Comment by javiereguiluz** [comment]
I've looked into https://github.com/php-http/client-common/blob/2.x/.github/workflows/tests.yml but I don't know where to put the tests for upcoming Symfony versions. You test "latest PHP", "lowest PHP" and "Symfony LTS".

**Comment by Chris53897** [comment]
I did a quick check.
https://github.com/Chris53897/client-common/actions/runs/6744709040/job/18335087941
https://github.com/Chris53897/client-common/blob/feature/support-symfony-7/.github/workflows/tests.yml#L96

It is blocked by https://github.com/phpspec/phpspec/blob/main/composer.json#L24
I created a PR https://github.com/phpspec/phpspec/pull/1452

**Comment by dbu** [comment]
if phpspec is not moving quickly, i would be ok to merge this "blindly" and tag a patch version. the only component we use is options resolver, and that is really stable and no changes expected.

**Comment by Chris53897** [comment]
@dbu Can you please have a look again, after symfony 7 is released today?

**Comment by dbu** [comment]
tagged as https://github.com/php-http/client-common/releases/tag/2.7.1

@Chris53897 if phpspec releases a new version, glad if you could do a pull request to run tests with symfony 7 ;-)

**Comment by Chris53897** [comment]
Thanks. I did subscribed for releases on phpspec to get notified

**Pull request merged**
