### PR TITLE
Fix implicit nullable type to avoid PHP 8.4 warnings

### PR DESCRIPTION
**Pull request by eiriksm**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| Documentation   | if this is a new feature, link to pull request in https://github.com/php-http/documentation that adds relevant documentation
| License         | MIT

#### What's in this PR?

This PR makes the implicit nullable type explicit. Using implicit nullable types has been deprecated, and will emit deprecation warnings in PHP 8.4

#### Why?

To avoid getting deprecation warnings in PHP 8.4

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Can we add PHP 8.4 to the CI, too?

**Comment by eiriksm** [comment]
>Can we add PHP 8.4 to the CI, too?

done :nerd_face:

**Comment by GrahamCampbell** [comment]
Fixes similar to https://github.com/php-http/httplug/pull/176 are needed.

**Comment by eiriksm** [comment]
added the "emulate php 8.3" part, but not sure which tweak is needed to fix phpcs. Which by the way should probably be a separate PR, as it does not relate to the changes in this PR

**Comment by GrahamCampbell** [comment]
The tweak is needed to get it to pass, because the symfony ruleset has changed and the php-cs-fixer version is not pinned.

**Comment by dbu** [comment]
i updated the cs fixer and apply the fixes in #248. that includes the `?` for nullable parameters.

can you please rebase on the 2.x branch? that should make the cs fixer green.

**Comment by eiriksm** [comment]
✅

**Review by dbu — APPROVED** [review]
thanks a lot!

**Comment by eiriksm** [comment]
amazing. thank you so much for being so responsive :smile: 

Any chance we could also cut a new release with this change? :nerd_face:

**Comment by dbu** [comment]
thanks for contributing. i tagged the release: https://github.com/php-http/client-common/releases/tag/2.7.2

**Pull request merged**
