### PR TITLE
[2.0] Remove deprecations

### PR DESCRIPTION
**Pull request by Jean85**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | partially #115
| License         | MIT

#### What's in this PR?
This PR drops the only deprecation present in 1.x branch.

#### Checklist
- [x] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [x] Documentation pull request created (not needed)

### CODE REVIEW

**Comment by dbu** [comment]
thank you!

**Comment by Jean85** [comment]
Can you add the 2.0 milestone here?

**Comment by sagikazarmark** [comment]
Done

**Comment by rtripault** [comment]
I believe you also might want to remove anything related to `debug_plugins` optin in `PluginClient::createPluginChain`

**Comment by dbu** [comment]
indeed. @Jean85 would you mind doing another pull request to remove all mentions of debug_plugins in this file? and can you check the rest of the repository if its mentioned anywhere else, like in the documentation?

**Comment by Jean85** [comment]
@dbu completed in #119; no other mention of it in the whole project, apart from the changelog.

**Comment by dbu** [comment]
thanks! yeah we want to keep the changelog ;-)

**Pull request merged**
