### PR TITLE
Fixed pretty-ci setup

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by dbu** [comment]
can we disable the pretty-ci checks that force the additional cleanup? otherwise we should turn off pretty-ci in master completely to not have failing builds.

**Comment by Nyholm** [comment]
Im not sure... 

In my mind we release 1.9, create a new branch from that and then merge 2.x. So Im fine with pretty CI is red for the last few PRs before 1.9

**Comment by dbu** [comment]
if we can disable pretty-ci on the 1.9 or 1.x branch we create, i am fine with that. i want to avoid having red tests on the legacy version for as long as possible.

**Comment by dbu** [comment]
this is obsolete as we move to 2.x now.

**Pull request closed without merging**
