### PR TITLE
Test on PHP 7.1

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

#### What's in this PR?

Adds PHP 7.1 to the travis test matrix.

#### Why?

PHP 7.1 is coming later this year, and it would be good to verify compatibility.

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

#### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Can you please open a PR in our boilerplate repo too? Thanks

**Comment by GrahamCampbell** [comment]
Yeh. :)

**Comment by sagikazarmark** [comment]
Can you please change the before_install line to `- if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi` to see if it fixes the build?

**Comment by sagikazarmark** [comment]
Great, thanks. 👍 
Can you please apply this fix to the other PRs too?

**Pull request merged**
