### PR TITLE
Improved performance of QueryDefaultsPlugin

### PR DESCRIPTION
**Pull request by vudaltsov**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | #67 
| Documentation   | 
| License         | MIT

### CODE REVIEW

**Comment by vudaltsov** [comment]
@dbu , yes.

`$requestQuery += $defaultQuery` will only add elements from __default query__ not existing in __request query__ (including the ones with numeric indexes) according to http://php.net/manual/en/language.operators.array.php, which is exactly the same as iterating over __default query__ and adding to __request query__ with `!isset` check.

The order will be preserved. The new array will contain elements from `$requestQuery` in their current order with added nonexisting elements from `$defaultQuery` in their original order. Same as it was before.

**Comment by vudaltsov** [comment]
Could this be merged? Or can I help somehow? Maybe add more tests?

**Comment by Nyholm** [comment]
Im not sure about this. A side effect (that I think I see):

```php
$defaults = ['foo'=>'bar'];
$query = ['foo' => 'newValue'];

// Running the plugin

$output = 'foo=bar&foo=newValue';
```

Right?

**Comment by vudaltsov** [comment]
No, the output will be `$output = 'foo=newValue'`. We parse the given query and merge default values into it (with existing values ignored). And then encode the clean query array and pass it to request.

My solution should give no side effects.

**Comment by Nyholm** [comment]
okey. Maybe I misread the code. Is there a test that cover this case?

**Comment by vudaltsov** [comment]
Sure! I hope I have time this weekend to commit such a test.

**Comment by vudaltsov** [comment]
done

**Comment by vudaltsov** [comment]
@Nyholm , let's merge it?

**Comment by joelwurtz** [comment]
Thanks for this @vudaltsov and sorry for the wait, yes let's merge this

**Pull request merged**
